### ISSUE TITLE
Minecolonies item recognition issue

### ISSUE THREAD

**Issue by Annon9007723** [SilentChaos512/Silent-Gear#328]
## Versions

- **Silent Gear**: 2.6.0+217
- **Silent's Gems**: 3.7.9+112 
- **Silent Lib**: 4.9.1+64
- **Forge**: 36.0.31
- **Modpack**: N/A 
- **Optifine Installed**: Yes (G6 Ultra)

## Expected Behavior

Items from SilentGear to be used in MineColonies.

## Actual Behavior

In cases of Armor, Swords, and Mattocks (Mattocks trying to replace Hoes, unsure if any other issues exist), the colonists will not attempt to use them. Even when the items are lower grade than the hut requires (A guard tower that is level 2 could use up to iron. While handing an archer a netherite coated diamond bow could work at level 1, handing a stone sword with a bone handle at level 2 to a knight will not work. Also, handing something like wool armor to a lvl 2 guard tower, be it knight or archer, neither will use it.)

## Links/Images

- (N/A)

## Steps to Reproduce the Problem

1. Proceed to launch the mods together (minecolonies on version 0.13.615-ALPHA tested)
2. Make a colony in creative mode on a new world
3. Make sure the guard tower is set to need a knight before attempting to hand them custom armor and swords from silent gear.

**Comment by SilentChaos512** [comment]
This _might_ be fixed in version 2.6.27, if anyone is available to test it.

**Comment by TheRealTNT99** [comment]
As of version 2.8.5, it's still an issue.

I tried giving my guard Silent Gear Wood Armor, but he doesn't recognise it.
Then I tried going into the compability section from the MineColonies Mod, to see if I can "add" tools, weapons and armor from Silent Gear (by tags), but that also didn't work.

I don't know, if this issue lies with Silent Gear or with MineColonies, but seeing that I found nearly the same issue here already, I thought I just post my experience here.

**Comment by Spazmunki13** [comment]
I can also confirm, in 2.8.7, this is still an issue.

**Comment by Annon9007723** [comment]
I guess to elaborate on this now...and this also being an issue with the 1.18.2-2.10.7 version. Except, more. I tested this with the tools, but not the armor yet. I'm wondering if this could be an issue with armor as well. Unsure about the fishing rod or bow. Though, they were using the shears thankfully, I'll test the rest later later. 

What specifically happened in testing is that they aren't able to use them during building levels 0-4 where they are restricted via materials. Like, they can only use Wood tools at level 0 (The builder can only use tools at level 0), stone at 1, iron at 2, so on and so forth. At 5 the builder was able to use all the tools. No matter the material. When the base material was wood the builder wouldn't use the tools (Pickaxe, axe, shovel) until they hit level 5. 

I'll test this with armor, shields, and fishing rods in a bit. Just testing this all in creative.

**Comment by SilentChaos512** [comment]
They might be going off the item's dummy vanilla "tool material" then. I could try changing it to level 0 to see if it makes any difference. If my theory is right, that would make it so any worker of any level could use any tool.

**Comment by Annon9007723** [comment]
That was a much faster response than I expected to get but thank you.

**Comment by Annon9007723** [comment]
Shields work right off the bat. No material restrictions. 

The fishing rod...is weird. As I made a wooden fishing rod with max grading to test it out, and the fisher is using it. Though, upon adding a silk binding and a leather grip the fisher stopped saying the fishing rod was not able to be used by the fisher. Changing the tool rod or the material of the tool itself would make it unusable by the level 1 fisher. And upon upgrading, the I change it out with a stone version...and it's usable. I assume the fishing rod has...some sort of material info to it. 

The armor works on tier 5 of the guard. Same for the sword. Any tiers below that, they won't use it. Maybe you can base the material reading off of what the fishing rod has? Or...something. I dunno if any of this helped.

**Comment by SilentChaos512** [comment]
I set all the gear items to use wood or leather tiers in version 2.10.8. Please let me know if that changes anything. I only have a few minutes a day to actually write code right now...

**Comment by Annon9007723** [comment]
Seems like it's working. I'll do some more testing but handing over tools to the builder made it work when the builder is at level 1. I'll test level 0 later but at least it's functioning.

For some reason even at level 5 guards aren't accepting the pants or the boots. They aren't showing up on the list of items they can use.

Fishing rod still functions the same as before. But I'll build it up to level 5 to see if I can use modifiers then on the fishing rod.

**Comment by SilentChaos512** [comment]
Hmm, that's good to know. It would be nice if I could restrict tool usage according to the tier of the tool and level of the worker, but this is good for now.

Not sure why the armor isn't working. That will require some digging...

**Comment by Annon9007723** [comment]
Good news is now the grip and the binding seem to work on the fishing rod. I just decided to test that out of the blue. Not sure about level 1 fishing hut but I know the level 2 one works. Upgrading the tool to have iron in it with some bits of gold to increase synergy seems to be working. Giving them things like crimson steel in any part seems to invalidate the rod. Might be because it's crimson steel and azure electrum, I'll try upgrading them to level 5 when I can to test more but...this does need a lot more digging. 

A level 1 builder was using the crimson steel paxel so I guess that works for that. Might just need to play along with not giving them things that are...too out of their reach.

**Comment by ThePebblemancer** [comment]
My knowledge on the status of this bug might be a bit lackluster, but I'm testing the interactions between these and it seems that a lvl1 Guard Tower's guards can wear Steel armor with Leather bindings no problem, while lvl1 Builders can wield Invar axes just fine, but the mining speed doesn't (ssem to) change a lot from Stone. I still gotta test if swords deal and armor protects the expected amount of damage, byt I've seen some people saying that giving a 20 damage sword makes it do 3 points of damage (source: https://www.reddit.com/r/allthemods/comments/10k6q91/silent_gear_weapons_and_minecolonies/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button we play the same modpack, so it might be that)
